//! Pick from a pool of music
//!
//! Would like to use AI generated music or scrape from external site in the future

use std::collections::HashMap;

use lazy_static::lazy_static;
use rand::seq::SliceRandom;
use serde::{de::DeserializeOwned, Deserialize, Serialize};

#[derive(Serialize, Deserialize, PartialEq, Eq, Hash, Debug, Clone, Copy)]
pub enum Theme {
    Funky,
    Calm,
    Dark,
    Inspirational,
    Bright,
    Dramatic,
    Happy,
    Romantic,
    Angry,
    Sad,
}

pub fn choose_music(theme: &Theme) -> String {
    let list = MUSIC_DIR.get(theme).unwrap();
    let rand = list.choose(&mut rand::thread_rng()).unwrap();
    rand.to_string()
}

// URLS fetched using
// youtube-dl -j --flat-playlist <playlist-url> | jq -r '.id'
lazy_static! {
    pub static ref MUSIC_DIR: HashMap<Theme, Vec<&'static str>> = HashMap::from_iter([
        (
            Theme::Funky,
            vec![
                "ASjQab3NLFo",
                "EV9e9utb3qw",
                "P4y2CHgdr3I",
                "7CWAXjI-V20",
                "bsovxfhRH7E",
                "fvIzh20U59s",
                "Igr2427YziE",
                "TPZ6oLhIOjM",
                "x6q9AxPUTOs",
                "rSXn3XbkzNY",
                "mQY8Ax0DoJw",
                "YHtYjD7KwlY",
                "pyHVqrtkvTA",
                "Vyksvf9gBzw",
                "LzTdv4GNW8U",
                "lZCW1KUF8vM",
                "5P81GpnuA-g",
                "wapJp1H5I6k",
                "b4TRHgtNoys",
                "HpO6jpMp_Tk",
            ]
        ),
        (
            Theme::Calm,
            vec![
                "EV9e9utb3qw",
                "ASjQab3NLFo",
                "t_0Zyec7b14",
                "WAQjW-n1_Q8",
                "a8QK1mraRn0",
                "a3udYx-YE9s",
                "LXH7vwio7iA",
                "Igr2427YziE",
                "3uuGjiqtSXA",
                "P4y2CHgdr3I",
                "wapJp1H5I6k",
                "TPZ6oLhIOjM",
                "ocs9yzwHYIA",
                "IXs_LDA93YY",
                "fYJyjG9VWDI",
                "3zpucoZc3ZQ",
                "kqn9TLCcZnQ",
                "WL_uXfKTajw",
                "wE8QonXW5Qc",
                "aDSKJl_2XDc",
            ]
        ),
        (
            Theme::Dark,
            vec![
                "ASjQab3NLFo",
                "Igr2427YziE",
                "P4y2CHgdr3I",
                "U5NLq6bgY3M",
                "t7107-a1M9M",
                "hLfQZCZKKzw",
                "RRHnzZ9bkk8",
                "wE8QonXW5Qc",
                "1WUUA-4ENB4",
                "mdkt3wWCQeg",
                "QOUwaZZ2SQg",
                "jRZ4gg2Sp_0",
                "8T9rx2UIs1I",
                "5P81GpnuA-g",
                "sokxvhrgILY",
                "dxXUI9TKP20",
                "lZCW1KUF8vM",
                "9MNPt-zlz-8",
                "SLNbJmDNSeM",
                "kG_SWvzsM4Q",
            ]
        ),
        (
            Theme::Inspirational,
            vec![
                "EV9e9utb3qw",
                "ASjQab3NLFo",
                "P4y2CHgdr3I",
                "mw2DbE55P10",
                "5P81GpnuA-g",
                "EOAPMhaCtuw",
                "JGZpnYx71cQ",
                "U5NLq6bgY3M",
                "Igr2427YziE",
                "TPZ6oLhIOjM",
                "m3Bd1vGJNKo",
                "wE8QonXW5Qc",
                "Om-v_7cVMqg",
                "hrcRsa9RHZo",
                "MLGHO5OA6cQ",
                "3zpucoZc3ZQ",
                "bUXxFUg6wbM",
                "lZCW1KUF8vM",
                "ocs9yzwHYIA",
                "CepSVdTYXNc",
            ]
        ),
        (
            Theme::Bright,
            vec![
                "ASjQab3NLFo",
                "Uhmyz3gj09A",
                "EV9e9utb3qw",
                "QRvjLoxIuOU",
                "l788mVn6a1o",
                "GXxdkrr2RJA",
                "-9zkMQS20qM",
                "JGZpnYx71cQ",
                "Igr2427YziE",
                "xJEwYXJRLFg",
                "TPZ6oLhIOjM",
                "DmmWa-Fnxms",
                "fHXkGKVsRbo",
                "mQY8Ax0DoJw",
                "RRHnzZ9bkk8",
                "1WEAJ-DFkHE",
                "PQbFyY-C5Q8",
                "x6q9AxPUTOs",
                "LUPaZMbwsFg",
                "wE8QonXW5Qc",
            ]
        ),
        (
            Theme::Dramatic,
            vec![
                "x6q9AxPUTOs",
                "mnLWWpAMhJc",
                "u8uf7nsy5yw",
                "r9e1QZhs2Vw",
                "TekEzCCdnKg",
                "VAuWCRpoO74",
                "EV9e9utb3qw",
                "S8z2kZYA6k4",
                "b4TRHgtNoys",
                "ZRtdQ81jPUQ",
                "jfKfPfyJRdk",
                "R7_fpfTa2ms",
                "UHaVoyUEBBI",
                "Igr2427YziE",
                "NwXdmvaPFO4",
                "pyHVqrtkvTA",
                "rSXn3XbkzNY",
                "ASjQab3NLFo",
                "_6U5_m28jqI",
                "0Cxuz83Qwcc",
            ]
        ),
        (
            Theme::Happy,
            vec![
                "ASjQab3NLFo",
                "x5IvggHqvPc",
                "Igr2427YziE",
                "zVwtrra2WQQ",
                "SVIwHNTjeHQ",
                "aM81uF7eIKU",
                "6WZ67f9M3RE",
                "TPZ6oLhIOjM",
                "pyHVqrtkvTA",
                "5Kq2XeBOoQo",
                "n_uFzLPYDd8",
                "R7_fpfTa2ms",
                "jfKfPfyJRdk",
                "cEbiTGNPpek",
                "t7107-a1M9M",
                "EV9e9utb3qw",
                "brI7C7OM8HA",
                "TDIJK8HQj5M",
                "CG_-5ALE8C0",
                "QOUwaZZ2SQg",
            ]
        ),
        (
            Theme::Romantic,
            vec![
                "ASjQab3NLFo",
                "Gic-cXYJwGE",
                "P4y2CHgdr3I",
                "KYMQI50FCf0",
                "PvzIQNm0fBo",
                "c_vh7goD9O0",
                "wE8QonXW5Qc",
                "mdkt3wWCQeg",
                "zwv8HGJfB-I",
                "TPZ6oLhIOjM",
                "ZCxPGZcwaF8",
                "C7CsFZ0g_mM",
                "hLfQZCZKKzw",
                "3uuGjiqtSXA",
                "4DQ6YTej9Z4",
                "p9dNQ135ZwI",
                "OIDuiKyaZqE",
                "fs4n7h05GXk",
                "wx0Pe__I0js",
                "wFj7d_fnYTU",
            ]
        ),
        (
            Theme::Angry,
            vec![
                "EV9e9utb3qw",
                "ASjQab3NLFo",
                "Igr2427YziE",
                "cBp-rj2oRYY",
                "P4y2CHgdr3I",
                "TPZ6oLhIOjM",
                "f-ZK-h3DNPo",
                "5P81GpnuA-g",
                "6jJRfCKTypI",
                "WAQjW-n1_Q8",
                "ysfmCftjopY",
                "nCxc1trIMoA",
                "0BnzxXh-dp0",
                "uK1mZF_9G4I",
                "chRisUAxFak",
                "URanjYhrgaY",
                "GpX59xRKjT8",
                "3zpucoZc3ZQ",
                "MShqwOig3EE",
                "MLGHO5OA6cQ",
            ]
        ),
        (
            Theme::Sad,
            vec![
                "liwlFBDCo4c",
                "RThxmffrwIo",
                "PWRycHMM5ho",
                "rpwSr6z0v4k",
                "UWS7uMBZsJs",
                "ZuAMtopeI20",
                "v5b5juZL2CI",
                "XHE0Rpx7kV8",
                "wjbMpkvJ3uk",
                "AyVcSAaJlH0",
                "YPWcX1hCetc",
                "5PDYej1APkM",
                "PmtIs8E1Dhs",
                "ht0aCC1blxY",
            ]
        ),
    ]);
}
